version: "2"
run:
  build-tags:
    - integration
linters:
  enable:
    - bodyclose
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gocyclo
    - godot
    - gosec
    - misspell
    - nestif
    - revive
    - testpackage
    - unconvert
    - usestdlibvars
    - usetesting
    - whitespace
    - wsl_v5
  settings:
    revive:
      rules:
        - name: bare-return
        - name: blank-imports
        - name: duplicated-imports
        - name: defer
        - name: dot-imports
        - name: early-return
        - name: errorf
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: exported
        - name: function-result-limit
          arguments:
            - 3
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: line-length-limit
          arguments:
            - 125
        - name: superfluous-else
        - name: range
        - name: receiver-naming
        - name: struct-tag
        - name: time-naming
        - name: unexported-naming
        - name: unexported-return
        - name: unnecessary-stmt
        - name: unused-parameter
        - name: unused-receiver
        - name: var-declaration
        - name: var-naming
    usetesting:
      os-setenv: true
      os-temp-dir: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - testdata
      - third_party$
      - builtin$
      - examples$
issues:
  fix: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - testdata
      - third_party$
      - builtin$
      - examples$
