kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # video-game api
      - containerPort: 17020
        hostPort: 17020
      # Postgres
      - containerPort: 5432
        hostPort: 5432
      # Redis
      - containerPort: 6379
        hostPort: 6379
