// Code generated by mockery v2.42.0. DO NOT EDIT.

package twitch

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTwitchClient is an autogenerated mock type for the Twitch type
type MockTwitchClient struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: _a0
func (_m *MockTwitchClient) Authenticate(_a0 context.Context) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTwitchClient creates a new instance of MockTwitchClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTwitchClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTwitchClient {
	mock := &MockTwitchClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
