apiVersion: v1
kind: Namespace
metadata:
  name: video-game

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: video-game

spec:
  selector:
    matchLabels:
      app: redis

  serviceName: redis-service
  replicas: 1
  
  template:
    metadata:
      labels:
        app: redis

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 5
      
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: video-game

spec:
  selector:
    app: redis

  type: ClusterIP

  ports:
    - name: redis
      port: 6379
      targetPort: redis
