name: Tests

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches: [master]
    tags-ignore: ["**"]

env:
  GO_VERSION_FILE: "go.mod"
  CHECK_LATEST: true

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GO_VERSION_FILE }}
          check-latest: ${{ env.CHECK_LATEST }}
          cache: false
      -
        name: Pull dependencies
        run: go mod vendor
      -
        name: Unit tests
        run: make test
      -
        name: Linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          skip-cache: true
      -
        name: Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GO_VERSION_FILE }}
          check-latest: ${{ env.CHECK_LATEST }}
          cache: false
      -
        name: Pull dependencies
        run: go mod vendor
      -
        name: Build binary
        run: make build-linux-amd64
      -
        name: Integration tests
        run: make test-integration
